/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/shared/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        black: "#1D1D1D",
        default: "#FFFFFF",
        primary_50: "#F6F5FD",
        primary_100: "#EEECFB",
        primary_200: "#E0DCF8 ",
        primary_300: "#C8BFF3",
        primary_400: "#AC9AEB",
        primary_500: "#8F71E1",
        primary_600: "#7E53D4",
        primary_700: "#6F42C1",
        primary_800: "#5C36A1",
        primary_900: "#4D2E84",
        primary_950: "#2F1C59",
      },
      fontFamily: {
        manrope: ["Manrope", "sans-serif"],
      },
      fontSize: {
        body: "16px",
        title: "19px",
        caption_1: "13px",
        caption_2: "11px",
        heading_1: "48px",
        heading_2: "40px",
        heading_3: "33px",
        heading_4: "28px",
        heading_5: "23px",
        heading_6: "16px",
      },
      fontWeight: {
        body_semibold: 600,
        title_semibold: 600,
        caption_1_semibold: 600,
        caption_2_semibold: 600,
        heading_1_semibold: 600,
        heading_2_semibold: 600,
        heading_3_semibold: 600,
        heading_4_semibold: 600,
        heading_5_semibold: 600,
        body_bold: 700,
        title_bold: 700,
        caption_1_bold: 700,
        caption_2_bold: 700,
        heading_1_bold: 700,
        heading_2_bold: 700,
        heading_3_bold: 700,
        heading_4_bold: 700,
        heading_5_bold: 700,
      },
    },
  },
  plugins: [],
};
